# Generated by Django 5.2.5 on 2025-08-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_patient_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='province_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='region_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
