# Generated by Django 5.2.5 on 2025-08-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_country_id_patient_district_id_and_more'),
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='region_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubigeo.region'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubigeo.district'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubigeo.province'),
        ),
    ]
