# Generated by Django 5.2.5 on 2025-08-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_department_remove_patient_district_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='secondary_phone',
        ),
    ]
