# Generated by Django 5.2.4 on 2025-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationcode',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userverificationcode',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
