# Generated by Django 5.2.4 on 2025-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_userverificationcode_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationcode',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
