# Generated by Django 5.2.4 on 2025-08-09 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_userverificationcode_failed_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userverificationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='code',
            field=models.CharField(help_text='Código de verificación', max_length=10),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='expires_at',
            field=models.DateTimeField(help_text='Fecha y hora de expiración'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Intentos fallidos'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Si está bloqueado, hasta cuándo', null=True),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='user',
            field=models.ForeignKey(help_text='Usuario propietario del código', on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userverificationcode',
            index=models.Index(fields=['user', 'code'], name='user_verifi_user_id_564d97_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationcode',
            index=models.Index(fields=['expires_at'], name='user_verifi_expires_9bb582_idx'),
        ),
    ]
