# Generated by Django 5.2.5 on 2025-08-14 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_hour', models.TimeField(blank=True, null=True)),
                ('ailments', models.TextField(blank=True, max_length=1000, null=True)),
                ('diagnosis', models.TextField(blank=True, max_length=1000, null=True)),
                ('surgeries', models.TextField(blank=True, max_length=1000, null=True)),
                ('reflexology_diagnostics', models.TextField(blank=True, max_length=1000, null=True)),
                ('medications', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('appointment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('social_benefit', models.BooleanField(blank=True, null=True)),
                ('payment_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ticket_number', models.IntegerField(blank=True, null=True)),
                ('payment_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('therapist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('therapist_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='rooms.room')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='statuses.status')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-appointment_hour'],
                'unique_together': {('patient_id', 'appointment_date', 'appointment_hour')},
            },
        ),
    ]
